
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {concatTailwindClasses} from "@/lib/utils";
import React, {useCallback} from "react";
import ListItem from "@/components/ui/ListItem";
import {AuthProvider} from "@/lib/AuthContext";




const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {

    const headerCallbackfn = useCallback(
        //@ts-ignore
        (component) => (
            <ListItem
                key={component.title}
                title={component.title}
                href={component.href}
            >
                {component.description}
            </ListItem>
        ), []);
//     const breadCumbs: { title: string; href: string }[] = [
//         {
//             title: "Каталог",
//             href: "/"
//         },
//         {
//             title: "Наши магазины",
//             href: "/"
//         },
//         {
//             title: "Акции",
//             href: "/"
//         },
//         {
//             title: "Контакты",
//             href: "/"
//         },
//         {
//             title: "Вопросы",
//             href: "/"
//
//         },
//
//     ]
    return (
        <html lang="en">
        <body className={concatTailwindClasses(inter.className,
            'bg-background',
            'text-foreground',
            'flex',
            'items-center',
            'justify-center'
        )}><AuthProvider>

            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
